from loops.common.agent import AgentConfig, agent
from loops.common.git import commit_if_dirty, default_branch, get_diff, git, prepare_branch
from loops.common.github import (
    add_label,
    approved_issue_count,
    close_issue,
    comment_on_issue,
    create_issue,
    edit_issue_body,
    gh,
    issue_context,
    next_open_issue,
    open_autonomous_issues,
    open_autonomous_titles,
    open_pr,
    post_issues,
    remove_label,
)
from loops.common.logging import log
from loops.common.logs import make_run_dir, recent_run_summaries, write_step
from loops.common.preflight import run_fix_preflight, run_groom_preflight, run_scan_preflight
from loops.common.projects import (
    ROOT,
    load_project,
    project_context,
    run_command,
    run_tests,
    scan_context,
)

__all__ = [
    "ROOT",
    "AgentConfig",
    "add_label",
    "agent",
    "approved_issue_count",
    "close_issue",
    "comment_on_issue",
    "commit_if_dirty",
    "create_issue",
    "default_branch",
    "edit_issue_body",
    "get_diff",
    "gh",
    "git",
    "issue_context",
    "load_project",
    "log",
    "make_run_dir",
    "next_open_issue",
    "open_autonomous_issues",
    "open_autonomous_titles",
    "open_pr",
    "post_issues",
    "prepare_branch",
    "project_context",
    "recent_run_summaries",
    "remove_label",
    "run_command",
    "run_fix_preflight",
    "run_groom_preflight",
    "run_scan_preflight",
    "run_tests",
    "scan_context",
    "write_step",
]
